# Generated by Django 2.2.7 on 2019-12-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20191101_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Quiz',
        ),
    ]
